# Generated by Django 6.0.4 on 2026-05-17 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activites',
            fields=[
                ('IdAct', models.AutoField(primary_key=True, serialize=False)),
                ('denomination', models.CharField(max_length=50, verbose_name='Dénomination Activité')),
                ('photo', models.ImageField(upload_to='photos/Activites')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('idDepart', models.AutoField(primary_key=True, serialize=False)),
                ('denomination', models.CharField(max_length=20, verbose_name='Denomination Departement')),
                ('description', models.CharField(max_length=25, verbose_name='Description Departement')),
                ('NbrMembre', models.IntegerField(verbose_name='Nombre de Membre')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Intervenant',
            fields=[
                ('idInter', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=25, null=True, verbose_name="Nom de l'intervenant")),
                ('prenom', models.CharField(max_length=25, null=True, verbose_name="Prenom de l'intervenant")),
                ('postnom', models.CharField(max_length=25, null=True, verbose_name="Postnom de l'intervenant")),
                ('photo', models.ImageField(null=True, upload_to='photos/Intervenants')),
                ('tel', models.CharField(max_length=25, verbose_name='Telephone')),
            ],
        ),
        migrations.CreateModel(
            name='meditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=25, verbose_name='Theme méditation')),
                ('verset', models.CharField(max_length=25, verbose_name='verset')),
                ('message', models.TextField(verbose_name='message')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membres',
            fields=[
                ('idMembre', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=25, null=True, verbose_name='Nom Membre')),
                ('prenom', models.CharField(max_length=25, null=True, verbose_name='Prenom Membre')),
                ('postnom', models.CharField(max_length=25, null=True, verbose_name='PostNom Membre')),
                ('photo', models.ImageField(null=True, upload_to='photos/Membres/')),
                ('tel', models.CharField(max_length=13, null=True, verbose_name='téléphone')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('idCatg', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=25, null=True)),
                ('idAct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestDepartements.activites', verbose_name='Id Activités')),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_Intervention', models.DateField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('idAct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestDepartements.activites', verbose_name='Id Activité')),
                ('idInter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestDepartements.intervenant', verbose_name='Id intervenant')),
            ],
        ),
        migrations.CreateModel(
            name='Evolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Periode_evolution', models.DurationField(verbose_name="Periode d'evolution")),
                ('idDepart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestDepartements.departement', verbose_name='Id departement')),
                ('idMembre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestDepartements.membres', verbose_name='Id Membre')),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('idAct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestDepartements.activites', verbose_name='Id Activités')),
                ('idMembre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestDepartements.membres', verbose_name='Id Membres')),
            ],
        ),
    ]
