# Generated by Django 6.0.4 on 2026-04-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestDepartements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='meditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=25, verbose_name='Theme méditation')),
                ('verset', models.CharField(max_length=25, verbose_name='verset')),
                ('message', models.TextField(verbose_name='message')),
            ],
        ),
    ]
