# Generated by Django 6.0.4 on 2026-07-01 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestDepartements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activites',
            name='description',
            field=models.TextField(null=True, verbose_name='Description Activité'),
        ),
    ]
