# Generated by Django 6.0.4 on 2026-09-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestDepartements', '0002_activites_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activites',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
